# Generated by Django 3.2.8 on 2021-11-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.CharField(max_length=16)),
                ('link', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RssItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('guid', models.CharField(max_length=36)),
                ('link', models.CharField(max_length=76)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=128)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.tickers')),
            ],
        ),
    ]
