# Generated by Django 3.2.8 on 2021-11-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickers',
            new_name='Nasdaqs',
        ),
        migrations.RenameField(
            model_name='nasdaqs',
            old_name='ticker_symbol',
            new_name='nasdaq_symbol',
        ),
    ]
