# Generated by Django 3.2.8 on 2021-11-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20211124_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssitem',
            name='link',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='rssitem',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
