# Generated by Django 3.2.8 on 2021-11-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20211124_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssitem',
            name='symbol',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='Nasdaqs',
        ),
    ]
