# Generated by Django 3.2.8 on 2021-11-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20211124_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssitem',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
