# Generated by Django 3.2.8 on 2021-11-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_rssitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssitem',
            name='link',
            field=models.CharField(max_length=256),
        ),
    ]
